### ISSUE TITLE
Logging in to multiple TeamCity servers using one AAD application

### ISSUE THREAD

**Issue by pqthompson** [JetBrains/teamcity-azure-active-directory#17]
I have multiple TeamCity servers and I'm trying to set up one Azure Active Directory application to log into them all. I can set multiple reply URLs in the application configuration in Azure, but when logging in to TeamCity the AD login page always redirects to the last reply URL added to the application configuration. The ideal behaviour would be that it redirects to the TeamCity configuration the login request was started from.

Is it possible to add the reply url into the authorisation request so that the AD login always redirects to the TeamCity server the login request came from?

**Comment by ekoshkin** [comment]
@pqthompson thank you for this feature request
please consider as a workaround - you can try to use JetBrains Hub which is a tool for authentication and its actually supports AD and its integration with TeamCity which is available.

**Comment by dtretyakov** [comment]
@pqthompson, please the [latest plugin build](https://plugins.jetbrains.com/plugin/9083-azure-active-directory) where while login specified reply URL of current TeamCity server.
