### ISSUE TITLE
Logout of Team City does not log out of Azure

### ISSUE THREAD

**Issue by DALDEI** [JetBrains/teamcity-azure-active-directory#25]
go to TC login page
Click link to Login via AD.
Directed to Outlook 365 
Enter user + password of a test user -- Logs into TC < ! YEA >

Log out of TC.
close all browser windows.
open browser
go to TC login page
Click link to Login via AD
Logs directly into TC with no option to choose a different name.
Open incognito window and repeat.
I have not found any way to 'forget' the log in user and be directed back to Outlook or Azure to re-enter a new user.   Its 'stuck' autheticated with the test user.

I can login using TC native login,  but all attempts to login via the same system logs directectly to TC without a choice of username.

My *guess* is a missing or incorrect logout URL for the SAML authentication.

See example from You Track, specifying a "Sign out URL"
![2017_03_24_09_52_39_saml_2 0_administration](https://cloud.githubusercontent.com/assets/286113/24297085/d83fe596-1077-11e7-9c25-143f5aa67a1e.png)

**Comment by erikbra** [comment]
Is it really desired to log out of the Azure AD account when you log out of TeamCity? I don't know if I would like to be logged out of portal.azure.com, portal.office.com, etc, etc, if I log out of TeamCity...

**Comment by dtretyakov** [comment]
@DALDEI, please the latest plugin build where is possible to specify `Consent` prompt type to select required account for Azure AD authentication. If you need to type user credentials each time you could use `Login` prompt type.
