### ISSUE TITLE
HTTP Status 400 - Marked request as unauthenticated since retrieved JWT 'nonce' claim doesn't correspond to current TeamCity session.

### ISSUE THREAD

**Issue by victornie92** [JetBrains/teamcity-azure-active-directory#32]
I have this problem when i try to login with Azure Active Directory, and I can't seem to find any solution? Someone has the same problem or maybe a solution?

**Comment by Shan11812** [comment]
@victornie92 did you find any solution??

**Comment by victornie92** [comment]
@Shan11812 No haven't found anything

**Comment by dtretyakov** [comment]
@victornie92, @Shan11812 it could happen when your TeamCity session was changed while SSO operation.

Could you please check that before and after login attempt TeamCity URL was not changed, e.g. http:// => https://. Also, please check that before and after login attempt `TCSESSIONID` cookie value was not changed.

**Comment by Shan11812** [comment]
@dtretyakov After restarting server and clearing cookies, it went through

**Comment by dtretyakov** [comment]
Please comment if it is still actual.

**Comment by alekseybarabash** [comment]
Hello, I installed plugin, configured TC (2018.2.4 (build 61678)) and setup Enterprise applications.
After try to login I have a problem:
400 Some of required claims were not found in parsed JWT. nonce - 744E97885355B4D198A9479192607634; name - null, oid - null

Does it possible to help?

**Comment by joshschmitter** [comment]
Looks like this issue was fixed with a plugin update: https://youtrack.jetbrains.com/issue/TW-66625
