### ISSUE TITLE
Unable to add  'Microsoft Azure Active Directory'  as HTTP Authentication Module on TeamCity Professional 2017.1.5 (build 47175)

### ISSUE THREAD

**Issue by gaurav8053** [JetBrains/teamcity-azure-active-directory#35]
I am not able to perform following steps on latest TC server, can you please help?
Add 'Microsoft Azure Active Directory' HTTP authentication module to your authentication configuration.

Specify valid 'App OAuth 2.0 authorization endpoint' and 'Client ID' retrieved from Azure Portal.

Use 'Log in using Azure Active Directory' link available on Login page to login via your Azure Active Directory account.

**Comment by dtretyakov** [comment]
@gaurav8053, did you managed to create `Web app / API` Azure AD application and specify Reply URL as [described here](https://github.com/JetBrains/teamcity-azure-active-directory#configuring-azure-active-directory)?

If so need to visit Administration -> Authentication page in TeamCity server, then press `Switch to advanced mode`, press `Add module` button, select `Microsoft Azure Active Directory` and press Add button.

Then in the list press Edit link and specify `App OAuth 2.0 authorization endpoint` from the Azure portal from App registrations page (click on Endpoints button) and Application ID for created Azure AD application and press Done.

Then after logout you will see `Log in using Azure Active Directory` link on the TeamCity login page: `%TeamCity_URL%/login.html`.

Please let me know if you have further questions.

**Comment by gaurav8053** [comment]
Hi,

Yes I was able to proceed ahead.
Apologies for not updating ticket and thanks for following up.

Regards,
Gaurav
