### ISSUE TITLE
Invalid redirect when TeamCity is hosted on subpath

### ISSUE THREAD

**Issue by lpatalas** [JetBrains/teamcity-azure-active-directory#37]
Hello.

I host TeamCity instance on subpath like `https://mydomain.com/teamcity/`, so login should redirect to `https://mydomain.com/teamcity/overview.html` but this plugin always redirects to `https://mydomain.com/overview.html`. I guess this may be caused by following line: https://github.com/JetBrains/teamcity-azure-active-directory/blob/8fa7dc9e4ff75bf8cd2c2ee6406b78dea707e729/azure-active-directory-server/src/main/kotlin/org/jetbrains/teamcity/aad/LoginViaAADController.kt#L45

Is this in fact a bug or just a matter of configuration?

Best regards,
Łukasz

**Comment by dtretyakov** [comment]
@lpatalas, it was fixed, could you please download the [latest plugin version](https://plugins.jetbrains.com/plugin/9083-azure-active-directory).
