### ISSUE TITLE
Error installing the 0.5 version of the plugin.

### ISSUE THREAD

**Issue by erichexter** [JetBrains/teamcity-azure-active-directory#39]
After loading the plugin, I get the following error.
Failed to enable authentication module: HTTP-AAD, error: Cannot find authentication module for type: HTTP-AAD. Please check the corresponding plugin is installed. See the attached screenshot.

![image](https://user-images.githubusercontent.com/114692/35051352-a9ecc82e-fb6a-11e7-8348-6ba99b989ff6.png)

The plugin thinkgs it is missing the plugin descriptor file (teamcity-plugin.xml)
![image](https://user-images.githubusercontent.com/114692/35051392-bb3b6072-fb6a-11e7-88b1-b784b759a227.png)

this is using 2017.1.2 (build 46812) on windows server 2012 R2 (Microsoft Windows [Version 6.3.9600])

**Comment by erichexter** [comment]
Also, the Azure Active Directory Authentication Module is not available in the Add Module dialog.
![image](https://user-images.githubusercontent.com/114692/35051722-848b78c2-fb6b-11e7-9f00-ccfed0bb1802.png)

**Comment by dtretyakov** [comment]
@erichexter, the original plugin archive should be named `azure-active-directory.zip`. It looks that you have repacked it. Please download the latest version from the [plugins repository](https://plugins.jetbrains.com/plugin/9083-azure-active-directory) and upload it on the Administration -> Plugins List page. 

If it helps please let me know.

**Comment by erichexter** [comment]
I did not realize it was published there, I downloaded it from the github release page. https://github.com/JetBrains/teamcity-azure-active-directory/releases
