### ISSUE TITLE
400 Marked request as unauthenticated since retrieved JWT 'nonce' claim doesn't correspond to current TeamCity session.

### ISSUE THREAD

**Issue by vladimirglazkov** [JetBrains/teamcity-azure-active-directory#49]
TeamCity Enterprise 2020.1.1 (build 78657)

I've tried to use both URLs:
https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize
https://login.microsoftonline.com/{tenant_id}/oauth2/authorize

TC is located behind Nginx.
Configured this way:
https://www.jetbrains.com/help/teamcity/how-to.html#HowTo...-Commonmisconfigurations

It works fine with previous release - TeamCity Enterprise 2020.1 (build 78475)

**Comment by SithVicious** [comment]
Unfortunately having this issue too.
Hosted behind IIS proxy

**Comment by Jevonius** [comment]
We're also seeing this, with an IIS proxy. Reverting to 2020.1 fixed it. Have tried the updated snapshot version release on 6th June with no joy.

**Comment by IlyaFomenko** [comment]
I've created the [bug](https://youtrack.jetbrains.com/issue/TW-66625) in our YouTrack. Please, watch it to get all future updates.

**Comment by SithVicious** [comment]
> I have a little workaround for the issue as long as there is no updated version of the plugin. Change the `sameSiteCookies="lax"` attribute to `sameSiteCookies="none"` inside the `TeamCity/webapps/ROOT/META-INF/context.xml` file and restart the server. Works fine for me and my team. All possible values for the `sameSiteCookie` attribute are documented here: https://tomcat.apache.org/tomcat-8.5-doc/config/cookie-processor.html

Brilliant! thank you David for this workaround, i can confirm it worked for me.

**Comment by musmuris** [comment]
We upgraded last night and have the same issue. Tried the same as above but now it gives
```403 Forbidden: Responding with 403 status code due to failed CSRF check: authenticated POST request is made, but neither tc-csrf-token parameter nor X-TC-CSRF-Token header are provided.. For a temporary workaround, you can set internal property teamcity.csrf.paranoid=false  and provide valid Origin=https://teamcity.morar.co header with your request```

**Comment by musmuris** [comment]
The new plugin mentioned in https://youtrack.jetbrains.com/issue/TW-66625 works for us.  Just installed latest and it's back.
