### ISSUE TITLE
Responding with 403 status code due to failed CSRF check

### ISSUE THREAD

**Issue by jachin84** [JetBrains/teamcity-azure-active-directory#51]
After authenticating with Azure AD I'm see the following error:

```
403 Forbidden: Responding with 403 status code due to failed CSRF check: authenticated POST request is made, but neither tc-csrf-token parameter nor X-TC-CSRF-Token header are provided.. For a temporary workaround, you can set internal property teamcity.csrf.paranoid=false  and provide valid Origin=https://<fqhn> header with your request
```

**Comment by SithVicious** [comment]
The error tells you what to do:  set internal property teamcity.csrf.paranoid=false
Admin > Diagnostics > Internal Properties

![Capture](https://user-images.githubusercontent.com/25457310/90348189-1f0f1180-e078-11ea-9977-960874f623d9.PNG)

**Comment by jachin84** [comment]
I have those settings in place already.

**Comment by bobbyinthedark** [comment]
I'm having the same issue. The error is pretty clear to use the paranoid=false setting as a **temporary** workaround, implying it's not suitable for production.

**Comment by SithVicious** [comment]
Perfect - this is working for me in latest update.

**Comment by jachin84** [comment]
Why is this issue closed? It is pretty clear from the error message in TeamCity that the workaround is **temporary**. What is the permanent solution to this issue that does not involve disabling security protocols?

**Comment by SithVicious** [comment]
> Why is this issue closed? It is pretty clear from the error message in TeamCity that the workaround is **temporary**. What is the permanent solution to this issue that does not involve disabling security protocols?

It was fixed in the latest version of the plugin.

https://github.com/JetBrains/teamcity-azure-active-directory/commit/546b31f27bc4d9f24fc3bc611562eaabf7141068

**Comment by IlyaFomenko** [comment]
Please install latest plugin version (0.7.0)
You can find corresponding YT ticket here: [https://youtrack.jetbrains.com/issue/TW-66220](https://youtrack.jetbrains.com/issue/TW-66220)
