### ISSUE TITLE
Hardcoded path after successful authentication prevents new UI adoption

### ISSUE THREAD

**Issue by hulvei3** [JetBrains/teamcity-azure-active-directory#53]
Because the redirect path is hardcoded to `/overview.html`, we always get the old UI until we either go to the root or remove the ".html".

This is a big point of annoyance for our devs - especially due to the short session time which makes us do this many times a day as stated in another issue.

For us a simple removal of the path segment below would suffice

https://github.com/JetBrains/teamcity-azure-active-directory/blob/546b31f27bc4d9f24fc3bc611562eaabf7141068/azure-active-directory-server/src/main/kotlin/org/jetbrains/teamcity/aad/LoginViaAADController.kt#L64

**Comment by IlyaFomenko** [comment]
Hi, @hulvei3!
Thank you for reporting it. I've created [the bug](https://youtrack.jetbrains.com/issue/TW-69037) in our YouTrack. Please, watch\vote it to get all future updates.

**Comment by IlyaFomenko** [comment]
Hi, @hulvei3!
Please try a new 0.7.2 version. 
We added an option to redirect to TC root. [Here](https://github.com/JetBrains/teamcity-azure-active-directory#switching-to-the-new-ui) is a short instruction.

**Comment by hulvei3** [comment]
Thanks for the fix and description. Works like a charm!
