### ISSUE TITLE
Change (or allow configuration of) how username, name and email account will be added to TeamCity from AD 

### ISSUE THREAD

**Issue by ghost** [JetBrains/teamcity-azure-active-directory#8]
I just tried the plugin and it adds the AD full name as TeamCity username, and adds nothing for name and email on TeamCity account.

It seems most 'natural' if it let the AD username and full name be TeamCity username and name, respectivelly, and the AD UPN be the TeamCity email.

Or maybe a configuration option could be added on the plugin the allow these mappings

**Comment by maartenba** [comment]
Would be nice. This also makes it possible to link existing users to AAD users?

**Comment by ekoshkin** [comment]
What JWT property d oyou expect to use as UPN
as for email - it is provided

**Comment by maartenba** [comment]
Ideally it can be mapped, e.g. by e-mail so that it can be linked to an existing user.

**Comment by ekoshkin** [comment]
@maartenba i gonna link existing users via email
the question is - what aad user jwt property to use as teamcity username

**Comment by maartenba** [comment]
Configurable? Or part of the email before @?

**Comment by ekoshkin** [comment]
why not to use name claim? full name of live id user is a given name and surname
so name is what we need - no?

**Comment by maartenba** [comment]
That's an option, too. Although name (as well as email) could potentially change. uid or oid I believe is the unique key.

**Comment by ekoshkin** [comment]
we already use oid to map teamcity user to aad user, so looks like all we need is to fill email and full name fields

**Comment by maartenba** [comment]
Would that also make it possible to link existing TeamCity users to an AAD identity? E.g. we have a number of users in TeamCity already but would like to link them to an AAD identity so we can turn off basic auth and have AAD only.

**Comment by ekoshkin** [comment]
It will be possible. But mapping via email required email to be trusted / verified.
So there will be an option in AAD auth schema settings - Accociate AAD user with existing TeamCity user via e-mail

**Comment by maartenba** [comment]
:+1:

**Comment by ekoshkin** [comment]
@andre-takenet i've failed to find mentioned properties in JWT retrieved from AAD. Could you please share an example of user profile and JWT?

**Comment by andre-takenet** [comment]
@ekoshkin, I don´t know how to get a JWT sample...
Can you give me some hints for how can I do this?

**Comment by ekoshkin** [comment]
@andre-takenet please take a look https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx

**Comment by andre-takenet** [comment]
@ekoshkin, I think the mapping could be:
TeamCity username -> unique_name
TeamCity name ->  given_name + family_name
TeamCity email -> upn
